language: php

matrix:
  allow_failures:
    - php: hhvm
    - php: 7

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
    - composer self-update
    - composer install --dev

script: vendor/bin/phpunit

